import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`CREATE TABLE \`pages_rels\` (
  	\`id\` integer PRIMARY KEY NOT NULL,
  	\`order\` integer,
  	\`parent_id\` integer NOT NULL,
  	\`path\` text NOT NULL,
  	\`images_id\` integer,
  	FOREIGN KEY (\`parent_id\`) REFERENCES \`pages\`(\`id\`) ON UPDATE no action ON DELETE cascade,
  	FOREIGN KEY (\`images_id\`) REFERENCES \`images\`(\`id\`) ON UPDATE no action ON DELETE cascade
  );
  `)
  await db.run(sql`CREATE INDEX \`pages_rels_order_idx\` ON \`pages_rels\` (\`order\`);`)
  await db.run(sql`CREATE INDEX \`pages_rels_parent_idx\` ON \`pages_rels\` (\`parent_id\`);`)
  await db.run(sql`CREATE INDEX \`pages_rels_path_idx\` ON \`pages_rels\` (\`path\`);`)
  await db.run(sql`CREATE INDEX \`pages_rels_images_id_idx\` ON \`pages_rels\` (\`images_id\`);`)
  await db.run(sql`ALTER TABLE \`pages\` ADD \`description\` text NOT NULL;`)
  await db.run(sql`ALTER TABLE \`pages\` ADD \`thumb_image_id\` integer REFERENCES images(id);`)
  await db.run(sql`CREATE UNIQUE INDEX \`pages_slug_idx\` ON \`pages\` (\`slug\`);`)
  await db.run(sql`CREATE INDEX \`pages_thumb_image_idx\` ON \`pages\` (\`thumb_image_id\`);`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`name\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xs_2x_webp_url\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xs_2x_webp_width\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xs_2x_webp_height\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xs_2x_webp_mime_type\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xs_2x_webp_filesize\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xs_2x_webp_filename\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xs_2x_avif_url\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xs_2x_avif_width\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xs_2x_avif_height\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xs_2x_avif_mime_type\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xs_2x_avif_filesize\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xs_2x_avif_filename\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_sm_2x_webp_url\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_sm_2x_webp_width\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_sm_2x_webp_height\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_sm_2x_webp_mime_type\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_sm_2x_webp_filesize\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_sm_2x_webp_filename\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_sm_2x_avif_url\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_sm_2x_avif_width\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_sm_2x_avif_height\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_sm_2x_avif_mime_type\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_sm_2x_avif_filesize\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_sm_2x_avif_filename\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_md_2x_webp_url\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_md_2x_webp_width\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_md_2x_webp_height\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_md_2x_webp_mime_type\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_md_2x_webp_filesize\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_md_2x_webp_filename\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_md_2x_avif_url\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_md_2x_avif_width\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_md_2x_avif_height\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_md_2x_avif_mime_type\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_md_2x_avif_filesize\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_md_2x_avif_filename\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_lg_2x_webp_url\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_lg_2x_webp_width\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_lg_2x_webp_height\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_lg_2x_webp_mime_type\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_lg_2x_webp_filesize\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_lg_2x_webp_filename\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_lg_2x_avif_url\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_lg_2x_avif_width\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_lg_2x_avif_height\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_lg_2x_avif_mime_type\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_lg_2x_avif_filesize\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_lg_2x_avif_filename\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xl_2x_webp_url\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xl_2x_webp_width\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xl_2x_webp_height\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xl_2x_webp_mime_type\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xl_2x_webp_filesize\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xl_2x_webp_filename\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xl_2x_avif_url\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xl_2x_avif_width\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xl_2x_avif_height\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xl_2x_avif_mime_type\` text;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xl_2x_avif_filesize\` numeric;`)
  await db.run(sql`ALTER TABLE \`images\` ADD \`sizes_xl_2x_avif_filename\` text;`)
  await db.run(sql`CREATE INDEX \`images_sizes_xs_2x_webp_sizes_xs_2x_webp_filename_idx\` ON \`images\` (\`sizes_xs_2x_webp_filename\`);`)
  await db.run(sql`CREATE INDEX \`images_sizes_xs_2x_avif_sizes_xs_2x_avif_filename_idx\` ON \`images\` (\`sizes_xs_2x_avif_filename\`);`)
  await db.run(sql`CREATE INDEX \`images_sizes_sm_2x_webp_sizes_sm_2x_webp_filename_idx\` ON \`images\` (\`sizes_sm_2x_webp_filename\`);`)
  await db.run(sql`CREATE INDEX \`images_sizes_sm_2x_avif_sizes_sm_2x_avif_filename_idx\` ON \`images\` (\`sizes_sm_2x_avif_filename\`);`)
  await db.run(sql`CREATE INDEX \`images_sizes_md_2x_webp_sizes_md_2x_webp_filename_idx\` ON \`images\` (\`sizes_md_2x_webp_filename\`);`)
  await db.run(sql`CREATE INDEX \`images_sizes_md_2x_avif_sizes_md_2x_avif_filename_idx\` ON \`images\` (\`sizes_md_2x_avif_filename\`);`)
  await db.run(sql`CREATE INDEX \`images_sizes_lg_2x_webp_sizes_lg_2x_webp_filename_idx\` ON \`images\` (\`sizes_lg_2x_webp_filename\`);`)
  await db.run(sql`CREATE INDEX \`images_sizes_lg_2x_avif_sizes_lg_2x_avif_filename_idx\` ON \`images\` (\`sizes_lg_2x_avif_filename\`);`)
  await db.run(sql`CREATE INDEX \`images_sizes_xl_2x_webp_sizes_xl_2x_webp_filename_idx\` ON \`images\` (\`sizes_xl_2x_webp_filename\`);`)
  await db.run(sql`CREATE INDEX \`images_sizes_xl_2x_avif_sizes_xl_2x_avif_filename_idx\` ON \`images\` (\`sizes_xl_2x_avif_filename\`);`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`DROP TABLE \`pages_rels\`;`)
  await db.run(sql`PRAGMA foreign_keys=OFF;`)
  await db.run(sql`CREATE TABLE \`__new_pages\` (
  	\`id\` integer PRIMARY KEY NOT NULL,
  	\`title\` text NOT NULL,
  	\`slug\` text NOT NULL,
  	\`updated_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
  	\`created_at\` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
  );
  `)
  await db.run(sql`INSERT INTO \`__new_pages\`("id", "title", "slug", "updated_at", "created_at") SELECT "id", "title", "slug", "updated_at", "created_at" FROM \`pages\`;`)
  await db.run(sql`DROP TABLE \`pages\`;`)
  await db.run(sql`ALTER TABLE \`__new_pages\` RENAME TO \`pages\`;`)
  await db.run(sql`PRAGMA foreign_keys=ON;`)
  await db.run(sql`CREATE INDEX \`pages_updated_at_idx\` ON \`pages\` (\`updated_at\`);`)
  await db.run(sql`CREATE INDEX \`pages_created_at_idx\` ON \`pages\` (\`created_at\`);`)
  await db.run(sql`DROP INDEX \`images_sizes_xs_2x_webp_sizes_xs_2x_webp_filename_idx\`;`)
  await db.run(sql`DROP INDEX \`images_sizes_xs_2x_avif_sizes_xs_2x_avif_filename_idx\`;`)
  await db.run(sql`DROP INDEX \`images_sizes_sm_2x_webp_sizes_sm_2x_webp_filename_idx\`;`)
  await db.run(sql`DROP INDEX \`images_sizes_sm_2x_avif_sizes_sm_2x_avif_filename_idx\`;`)
  await db.run(sql`DROP INDEX \`images_sizes_md_2x_webp_sizes_md_2x_webp_filename_idx\`;`)
  await db.run(sql`DROP INDEX \`images_sizes_md_2x_avif_sizes_md_2x_avif_filename_idx\`;`)
  await db.run(sql`DROP INDEX \`images_sizes_lg_2x_webp_sizes_lg_2x_webp_filename_idx\`;`)
  await db.run(sql`DROP INDEX \`images_sizes_lg_2x_avif_sizes_lg_2x_avif_filename_idx\`;`)
  await db.run(sql`DROP INDEX \`images_sizes_xl_2x_webp_sizes_xl_2x_webp_filename_idx\`;`)
  await db.run(sql`DROP INDEX \`images_sizes_xl_2x_avif_sizes_xl_2x_avif_filename_idx\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`name\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xs_2x_webp_url\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xs_2x_webp_width\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xs_2x_webp_height\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xs_2x_webp_mime_type\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xs_2x_webp_filesize\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xs_2x_webp_filename\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xs_2x_avif_url\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xs_2x_avif_width\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xs_2x_avif_height\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xs_2x_avif_mime_type\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xs_2x_avif_filesize\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xs_2x_avif_filename\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_sm_2x_webp_url\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_sm_2x_webp_width\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_sm_2x_webp_height\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_sm_2x_webp_mime_type\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_sm_2x_webp_filesize\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_sm_2x_webp_filename\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_sm_2x_avif_url\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_sm_2x_avif_width\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_sm_2x_avif_height\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_sm_2x_avif_mime_type\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_sm_2x_avif_filesize\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_sm_2x_avif_filename\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_md_2x_webp_url\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_md_2x_webp_width\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_md_2x_webp_height\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_md_2x_webp_mime_type\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_md_2x_webp_filesize\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_md_2x_webp_filename\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_md_2x_avif_url\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_md_2x_avif_width\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_md_2x_avif_height\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_md_2x_avif_mime_type\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_md_2x_avif_filesize\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_md_2x_avif_filename\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_lg_2x_webp_url\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_lg_2x_webp_width\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_lg_2x_webp_height\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_lg_2x_webp_mime_type\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_lg_2x_webp_filesize\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_lg_2x_webp_filename\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_lg_2x_avif_url\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_lg_2x_avif_width\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_lg_2x_avif_height\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_lg_2x_avif_mime_type\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_lg_2x_avif_filesize\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_lg_2x_avif_filename\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xl_2x_webp_url\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xl_2x_webp_width\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xl_2x_webp_height\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xl_2x_webp_mime_type\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xl_2x_webp_filesize\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xl_2x_webp_filename\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xl_2x_avif_url\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xl_2x_avif_width\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xl_2x_avif_height\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xl_2x_avif_mime_type\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xl_2x_avif_filesize\`;`)
  await db.run(sql`ALTER TABLE \`images\` DROP COLUMN \`sizes_xl_2x_avif_filename\`;`)
}
